name: Supabase Keep Alive

on:
  schedule:
    # Executes every monday and thursday at 0:00 UTC (every 3 to 4 days)
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # Allows to execute the workflow manually from Github

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Make a REST call to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/featured_games?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
